### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by andnasnd**

### CODE REVIEW

**Comment by andnasnd** [comment]
merge

**Comment by mistricky** [comment]
@andnasnd Hey! I have noticed that u wanna create ur own blog using the zzhack template. If you want I'm so glad to provide a template base zzhack which written in Rust & Yew for u :D

**Comment by andnasnd** [comment]
Hi Mist!

I’ve actually got the blog/site using your template (and will give PROPER thanks). 

At the moment, I’m struggling a bit with deployment - do I have to spin up an actix-server? I saw a vercel.json, but I’m not sure how to configure it to work with Yew. 

Thanks,
Anand

**Comment by mistricky** [comment]
I'm glad you can use my code to create your own website lol, can u create a discussion for these questions?  Discussion will be more suitable for QA

**Comment by andnasnd** [comment]
Hey Mist,

Went ahead and created a discussion in the zzhack repo! It’s a bit late for me at the moment (almost 3am lol), but I’ll be back bright and early tomorrow! 

Cheers,
Anand

**Comment by andnasnd** [comment]
Will do! Should I do it in the Discord server? I’m on it!

Anand

**Comment by mistricky** [comment]
@andnasnd I rarely use Discord, email me if u have any ideas

**Comment by andnasnd** [comment]
Oops nvm, I’ll do it in ZZhacks! Thanks

**Pull request closed without merging**
